"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _customers from './customers.bones.json'
import _dashboard from './dashboard.bones.json'
import _inventory from './inventory.bones.json'
import _products from './products.bones.json'
import _purchases from './purchases.bones.json'
import _sales from './sales.bones.json'
import _settings from './settings.bones.json'

registerBones({
  "customers": _customers,
  "dashboard": _dashboard,
  "inventory": _inventory,
  "products": _products,
  "purchases": _purchases,
  "sales": _sales,
  "settings": _settings,
})
